Repository DeveloperAcademy-POSTECH/2023-MC2-A-TEAM11-HYOZA, pull requests merged in 2023-05, with the labels that each got.

#20 Feat/tab list 1차 풀리퀘스트
  Hyoza.xcodeproj/project.xcworkspace/xcuserdata/semini.xcuserdatad/UserInterfaceState.xcuserstate
  Hyoza.xcodeproj/xcuserdata/semini.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Hyoza.xcodeproj/xcuserdata/semini.xcuserdatad/xcschemes/xcschememanagement.plist
  Hyoza/tabList/ListView.swift
Labels: ✨ Feature

#21 [Feat] #6 Publish View의 레이아웃을 구현했어요
  Hyoza.xcodeproj/project.pbxproj
  Hyoza/constant/CustomColor.swift
  Hyoza/extensions/ColorExtension.swift
  Hyoza/extensions/UIColorExtension.swift
  Hyoza/tabPublish/PeriodSegmentView.swift
  Hyoza/tabPublish/PeriodView.swift
  Hyoza/tabPublish/PublishView.swift
Labels: ✨ Feature

#25 Feat: QuerySentence 및 QuerySentenceManager 개발
  Hyoza/data/QuerySentenceManager.swift
  Hyoza/model/QuerySentence.swift
  Hyoza/raw/question_samples.json
Labels: ✨ Feature

#30 [Feat] TodayView
  Hyoza.xcodeproj/project.pbxproj
  Hyoza/tabToday/ClosedQuestionCardView.swift
  Hyoza/tabToday/ClosedQuestionsView.swift
  Hyoza/tabToday/QuestionBoxView.swift
  Hyoza/tabToday/QuestionCardView.swift
  Hyoza/tabToday/TodayView.swift
Labels: 🐞BugFix, ✨ Feature

#32 Feat/tab list
  Hyoza.xcodeproj/project.pbxproj
  Hyoza.xcodeproj/project.xcworkspace/xcuserdata/semini.xcuserdatad/UserInterfaceState.xcuserstate
  Hyoza/extensions/ViewExtension.swift
  Hyoza/tabList/ListView.swift
Labels: ✨ Feature

#38 [Feat] #6 PublishView
  Hyoza/tabPublish/PeriodSegmentView.swift
  Hyoza/tabPublish/PeriodView.swift
  Hyoza/tabPublish/PublishCardify.swift
  Hyoza/tabPublish/PublishView.swift
  Hyoza/tabPublish/ResultBookView.swift
Labels: ⚒️ Refactor

#47 Feat/tab list view
  Hyoza/tabList/ListView.swift
Labels: 🌈 Style

#52 Feat/today view
  Hyoza.xcodeproj/project.pbxproj
  Hyoza/tabToday/ClosedCardListView.swift
  Hyoza/tabToday/OpenCardView.swift
  Hyoza/tabToday/QuestionCardView.swift
  Hyoza/tabToday/TodayView.swift
Labels: 🐞BugFix, ✨ Feature

#57 [Feat] TodayView + CoreData
  Hyoza/data/Persistence.swift
  Hyoza/data/PersistenceController+Answer.swift
  Hyoza/data/PersistenceController+Question.swift
  Hyoza/extensions/NSPredicateExtension.swift
  Hyoza/qna/QnAView.swift
  Hyoza/tabList/ListView.swift
  Hyoza/tabToday/ClosedCardListView.swift
  Hyoza/tabToday/OpenCardView.swift
  Hyoza/tabToday/QuestionBoxView.swift
  Hyoza/tabToday/QuestionCardView.swift
  Hyoza/tabToday/TodayView.swift
Labels: ✨ Feature

#58 [Feat] ColorExtension 추가, PublishView + CoreData
  Hyoza.xcodeproj/project.pbxproj
  Hyoza/constant/CustomColor.swift
  Hyoza/data/Persistence.swift
  Hyoza/extensions/ColorExtension.swift
  Hyoza/extensions/DateExtension.swift
  Hyoza/extensions/IntExtension.swift
  Hyoza/extensions/NSPredicateExtension.swift
  Hyoza/extensions/UIColorExtension.swift
  Hyoza/tabPublish/MonthPickerView.swift
  Hyoza/tabPublish/PeriodView.swift
  Hyoza/tabPublish/PublishView.swift
Labels: ✨ Feature

#61 Feat/today view
  Hyoza/tabToday/QuestionCardView.swift
  Hyoza/tabToday/TodayView.swift
Labels: 🐞BugFix, ✨ Feature

#65 bugfix : "질문리스트뷰" - Q&A뷰에서 답변 수정했을때 리스트뷰에 반영안되는 문제 해결 - Resolve : #64
  Hyoza/tabList/ListView.swift
Labels: 🐞BugFix

#66 [Feat] TodayView + CoreData
  Hyoza.xcodeproj/project.pbxproj
  Hyoza/MainTabView.swift
  Hyoza/data/Persistence.swift
  Hyoza/data/PersistenceController+Question.swift
  Hyoza/raw/question_samples.json
  Hyoza/tabPublish/PublishView.swift
  Hyoza/tabToday/ClosedCardListView.swift
  Hyoza/tabToday/OpenCardView.swift
  Hyoza/tabToday/QuestionBoxView.swift
  Hyoza/tabToday/QuestionCardView.swift
  Hyoza/tabToday/TodayView.swift
Labels: ✨ Feature

#68 Feat/today view
  Hyoza/MainTabView.swift
  Hyoza/tabToday/ClosedCardListView.swift
  Hyoza/tabToday/OpenCardView.swift
  Hyoza/tabToday/QuestionBoxView.swift
  Hyoza/tabToday/QuestionCardView.swift
  Hyoza/tabToday/TodayView.swift
Labels: 🐞BugFix

#70 Feat/today view
  Hyoza/MainTabView.swift
  Hyoza/tabToday/ClosedCardListView.swift
  Hyoza/tabToday/OpenCardView.swift
  Hyoza/tabToday/QuestionBoxView.swift
  Hyoza/tabToday/QuestionCardView.swift
  Hyoza/tabToday/TodayView.swift
Labels: 🐞BugFix

#72 [Fix] CoreData + QnA 뷰 수정 + Publish View 수정
  Hyoza/HyozaApp.swift
  Hyoza/component/CardView.swift
  Hyoza/data/CoreDataHelper.swift
  Hyoza/data/Persistence.swift
  Hyoza/data/PersistenceController+Answer.swift
  Hyoza/data/PersistenceController+Question.swift
  Hyoza/qna/QnAView.swift
  Hyoza/tabPublish/MonthPickerView.swift
  Hyoza/tabPublish/PeriodSegmentView.swift
  Hyoza/tabPublish/PeriodView.swift
  Hyoza/tabPublish/PublishView.swift
  Hyoza/tabPublish/ResultBookView.swift
Labels: 🐞BugFix, ✨ Feature, ⚒️ Refactor

#77 Feat/tab list view
  Hyoza.xcodeproj/project.pbxproj
  Hyoza/component/CardView.swift
  Hyoza/tabList/ListView.swift
Labels: 🌈 Style

#88 Fix/answer
  Hyoza/Assets.xcassets/Contents.json
  Hyoza/Assets.xcassets/questionBoxImage.imageset/Contents.json
  Hyoza/Assets.xcassets/questionBoxImage.imageset/questionBoxImage.png
  Hyoza/MainTabView.swift
  Hyoza/data/PersistenceController+Question.swift
  Hyoza/extensions/NSPredicateExtension.swift
  Hyoza/qna/QnAView.swift
  Hyoza/tabList/ListView.swift
  Hyoza/tabToday/ClosedCardListView.swift
  Hyoza/tabToday/OpenCardView.swift
  Hyoza/tabToday/QuestionBoxView.swift
  Hyoza/tabToday/QuestionCardView.swift
  Hyoza/tabToday/TodayView.swift
Labels: 🐞BugFix

#92 [Style] 전반적 style 수정
  Hyoza.xcodeproj/project.pbxproj
  Hyoza/component/ButtonView.swift
  Hyoza/component/DifficultyCapsuleView.swift
  Hyoza/extensions/DateExtension.swift
  Hyoza/onboard/OnboardingView.swift
  Hyoza/qna/QnAView.swift
  Hyoza/raw/question_samples.json
  Hyoza/tabList/ListView.swift
  Hyoza/tabPublish/MonthPickerView.swift
  Hyoza/tabPublish/PeriodSegmentView.swift
  Hyoza/tabPublish/PeriodView.swift
  Hyoza/tabPublish/PublishCardify.swift
  Hyoza/tabPublish/PublishView.swift
  Hyoza/tabToday/ClosedCardListView.swift
  Hyoza/tabToday/OpenCardView.swift
  Hyoza/tabToday/QuestionBoxView.swift
  Hyoza/tabToday/QuestionCardView.swift
  Hyoza/tabToday/TodayView.swift
Labels: 🌈 Style

#98 [hotfix] PublishView crash 문제 + JSON 수정
  Hyoza/raw/question_samples.json
  Hyoza/tabPublish/PeriodView.swift
Labels: 🐞BugFix

#101 Fix/answer
  Hyoza.xcodeproj/project.pbxproj
  Hyoza/MainTabView.swift
  Hyoza/tabToday/ClosedCardListView.swift
Labels: 🐞BugFix

#100 chore: 더미데이터 JSON 오타 수정
  Hyoza/raw/question_samples.json
  Hyoza/tabPublish/PublishView.swift
Labels: 🌈 Style
